/**:
  ros__parameters:
    input: lsl
    policy: tbr
    calibrate: false
    calib_offset: 0.0
    calib_scale: 1.0
    lsl_stream_type: EEG
    lsl_timeout: 8.0
    lsl_source_id: ''
    role: steering
    cmd_topic: /eeg_cmd_vel/steering
    analysis_topic: /eeg_analysis/steering
    publish_hz: 20.0
    watchdog_sec: 0.5
    verbose: false
    analysis_verbose: false
    record_csv: false
    csv_path: /tmp/thymio_eeg_log_eeg2.csv
    max_forward_speed: 0.2
    reverse_speed: -0.15
    turn_forward_speed: 0.1
    turn_angular_speed: 1.2
    steer_deadzone: 0.1
    line_mode: ''
    blink_holdoff_frames: 4
    blink_confirm_frames: 2
